### PR TITLE
Mobley edits throughout

### PR DESCRIPTION
**Pull request by davidlmobley**
Here are my comments. I made some minor grammar fixes to the actual text throughout but everything more major basically appears as a comment in the TeX.

### CODE REVIEW

**Comment by davidlmobley** [comment]
I forgot to answer bullet points, @mrshirts :

> Author order – I put it in rough order of contribution as I understand it.  I’m happy to reorder as needed/desired.

No preferences here.

> What data is supporting information?  I imagine that the full converted files wouldn’t be, but the energy outputs could be. I’ve listed in the README of the github repository what could be distributed.

Why not put all the files? What's the file size for that? My preference these days is to basically try and provide _everything_ needed to do the whole thing again, because (a) it allows people to do exactly that, (b) it removes the burden of people asking me for scripts/files for whatever, and (c) it forces me to get the stuff organized in the way it ought to be long-term simply so I can deposit it. Though I admit this is more work. (If the files are too large I deposit them on a permanent external archival site which gives me a DOI and link to that.)

In your case you could argue since the files are already available with SAMPL5 this constitutes double-posting, but at least then you get them permanently tied to your paper rather than having them tied to D3R which isn't guaranteed to be as permanent (though we hope it will!). In other words if they are tied to SAMPL it's our job to keep them alive, whereas if they're tied to your paper it's the journal's job to keep them alive. :) 

Note that if you want more time to organize, you could submit now and organize your SI for revisions. :)

> Do we want to put the CHARMM files in the SAMPL5 tarball, even though the process is over? If it’s going to remain posted, it seems like that might be the best place. Or, we could not bother distributing them at all.

No strong feeling on this. 

Nothing on your other bullet points either.

**Comment by ctk3b** [comment]
I just added to @davidlmobley's edits. Let me know if you prefer to keep everything in separate PRs.

Regarding some of the larger questions:

> Should I talk more about ParmEd and InterMol internals or logic? 

I vote no. That would take up a lot of extra space that isn't necessarily required to support the results in this paper.

> What data to include in SI

Agreed on just posting everything. The lazy approach might just be to add them to this (or another) github repo and get a DOI from zenodo.

> Distribution coefficient data

Also agree on leaving this out. It shouldn't reveal anything not already demonstrated. 

One comment on the final discussion: Could we put together a concise, bulleted list of recommendations for others attempting conversions like this or do you feel that the details require more nuanced descriptions as currently presented?

**Comment by davidlmobley** [comment]
> Should I talk more about ParmEd and InterMol internals or logic?

I agree "no". You probably want to do this in a separate paper, otherwise you'll reduce the impact of what's here (some pretty important stuff about how there are some important differences between packages!). 

> Agreed on just posting everything. The lazy approach might just be to add them to this (or another) github repo and get a DOI from zenodo.

I'm fine with that, but I also recommend storing a copy of the repo in the SI anyway, even if it's just a zip file of exactly what's on GitHub. I've been using the analogy - imagine reading a Kirkwood paper from the early 1900s (some of these are still of interest!) and it says that, to receive a copy of the supporting information, you need send a telegraph to such-and-such an exchange in Kansas... It would now be impossible to retrieve the SI, since no one uses telegraphs, the exchange doesn't exist, and no one would be sitting there to send it back even if it did. Yet, in many important cases the JOURNAL is still alive. If the author had made the journal responsible for maintaining the SI, it would still be accessible presumably (since the PDF of the article is available online, even though PDFs didn't exist then!). So, in my view, unless copyright issues prohibit depositing materials in the SI (not the case here!) we should do so EVEN IF THEY ARE AVAILABLE ELSEWHERE just to make the journal responsible to maintain. I'm not really ready to place a heavy bet that Zenodo or GitHub will exist in 10 years, much less 50. And what about DOIs, or today's Internet even? The amount of work to deposit something in the SI is pretty trivial compared to the amount of headache it could save later. :) 

Of course, the flip side is also true - maybe the journal will go down, taking everything with it, long before GitHub, etc. goes down. So I'm not arguing for SI as **the authoritative place for supporting materials** but really just saying that we ought to put a copy there to help with archival.

**Comment by davidlmobley** [comment]
Oh, yes, and distribution coefficient data - I agree on leaving it out.

**Comment by ctk3b** [comment]
> I'm fine with that, but I also recommend storing a copy of the repo in the SI anyway, even if it's just a zip file of exactly what's on GitHub.

100% agree.

**Comment by swails** [comment]
GitHub and the journal with both almost certainly outlive InterMol and ParmEd (and possibly many of the programs we aim to support as well).

Not disagreeing with your point, but I'd put my money on the SI being useless for reasons beyond just GH possibly folding and/or the Journal folding if there comes a point in the future where that happens.

P.S. -- I am working on my response -- it will be in worst case late tonight.  Sorry for the delay!  This is a particularly bad week for me since my wife is out of town...

**Comment by davidlmobley** [comment]
> GitHub and the journal with both almost certainly outlive InterMol and ParmEd (and possibly many of the programs we aim to support as well).
> 
> Not disagreeing with your point, but I'd put my money on the SI being useless for reasons beyond just GH possibly folding and/or the Journal folding if there comes a point in the future where that happens.

I tend to agree with you **for this paper**, though I think it's worth developing the habit of just putting everything in the SI anyway given how difficult it is to predict whether any given paper might still be important to the field in X years. For example, I would have done a _much_ better job on supporting info for my 2006-2008 lysozyme papers if I knew what I know now, and knew that people would still be asking for those input files in 2016 and later. ;)

**Comment by davidlmobley** [comment]
@mrshirts - just to confirm on this, GitHub e-mailed me to say that you merged these, but only AFTER YOU e-mailed to say that you had submitted. Did the changes make it into the submission?

Thanks.

**Comment by mrshirts** [comment]
Yes, I upload after the submission to jcamd

**Pull request merged**
